services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - ayo4u
    ports:
      - 5432:5432
    volumes:
      - /postgres/data:/var/lib/postgresql/data

  conversion-api:
    build:
      context: ../
      dockerfile: ./Ayo4u.Server/Dockerfile
    container_name: conversion-api
    restart: unless-stopped
    ports:
      - 8010:8010
    networks:
      - ayo4u
    depends_on:
      - postgres

networks:
  ayo4u:
    name: ayo4u

volumes:
  postgres:
    driver: local 