services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - ayo4u
    ports:
      - 5432:5432
    volumes:
      - postgres:/data
      
networks:
  ayo4u:
    name: ayo4u

volumes:
  postgres:
    driver: local 